sudo: required

language: ruby

services:
  - docker

before_install:
  - docker build -t rhel73/datadog .
  - docker run -d -p 127.0.0.1:80:4567 rhel73/datadog /bin/sh -c 
  - docker ps -a
  - docker run rhel73/datadog /bin/sh -c

script:
  - bundle exec rake test
